version: "3"
services:
  frontend:
    image: react-frontend:0.1.0
    build:
      context: ./frontend/react-grpc
      dockerfile: ./Dockerfile
    container_name: grpc-frontend
    ports: 
      - "3000:3000"
    links: 
      - grpcwebproxy
  backend:
    image: node-backend:0.1.0
    build:
      context: ./backend/nodeServer
      dockerfile: ./Dockerfile
    container_name: grpc-backend
    # command: 
    #   - -grpc-port=8088 
    #   - -log-level=-1 
    #   - -log-time-format=2006-01-02T15:04:05.999999999Z07:00
    expose: 
      - "8088"
  grpcwebproxy:
    image: grpcwebproxy:0.9.5
    build:
      context: ./proxy/grpcwebproxy/
      dockerfile: ./Dockerfile
    container_name: grpc-proxy
    ports: 
      - "8080:8080"
    command: 
      - --backend_addr=dns:///backend:8088
      - --backend_tls_noverify=true
      - --run_tls_server=false
      - --use_websockets=true
      - --allow_all_origins
    links:
      - backend
