// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/ping_pong.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PongResponse struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongResponse) Reset()         { *m = PongResponse{} }
func (m *PongResponse) String() string { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()    {}
func (*PongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{1}
}

func (m *PongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongResponse.Unmarshal(m, b)
}
func (m *PongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongResponse.Marshal(b, m, deterministic)
}
func (m *PongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongResponse.Merge(m, src)
}
func (m *PongResponse) XXX_Size() int {
	return xxx_messageInfo_PongResponse.Size(m)
}
func (m *PongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PongResponse proto.InternalMessageInfo

func (m *PongResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type FetchPingCountRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPingCountRequest) Reset()         { *m = FetchPingCountRequest{} }
func (m *FetchPingCountRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPingCountRequest) ProtoMessage()    {}
func (*FetchPingCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{2}
}

func (m *FetchPingCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPingCountRequest.Unmarshal(m, b)
}
func (m *FetchPingCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPingCountRequest.Marshal(b, m, deterministic)
}
func (m *FetchPingCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPingCountRequest.Merge(m, src)
}
func (m *FetchPingCountRequest) XXX_Size() int {
	return xxx_messageInfo_FetchPingCountRequest.Size(m)
}
func (m *FetchPingCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPingCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPingCountRequest proto.InternalMessageInfo

func (m *FetchPingCountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type FetchPingCountResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Ping total count
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPingCountResponse) Reset()         { *m = FetchPingCountResponse{} }
func (m *FetchPingCountResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPingCountResponse) ProtoMessage()    {}
func (*FetchPingCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{3}
}

func (m *FetchPingCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPingCountResponse.Unmarshal(m, b)
}
func (m *FetchPingCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPingCountResponse.Marshal(b, m, deterministic)
}
func (m *FetchPingCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPingCountResponse.Merge(m, src)
}
func (m *FetchPingCountResponse) XXX_Size() int {
	return xxx_messageInfo_FetchPingCountResponse.Size(m)
}
func (m *FetchPingCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPingCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPingCountResponse proto.InternalMessageInfo

func (m *FetchPingCountResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FetchPingCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ServerStreamPingPongRequest struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	PingCount            int32    `protobuf:"varint,2,opt,name=ping_count,json=pingCount,proto3" json:"ping_count,omitempty"`
	PingInterval         int32    `protobuf:"varint,3,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStreamPingPongRequest) Reset()         { *m = ServerStreamPingPongRequest{} }
func (m *ServerStreamPingPongRequest) String() string { return proto.CompactTextString(m) }
func (*ServerStreamPingPongRequest) ProtoMessage()    {}
func (*ServerStreamPingPongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{4}
}

func (m *ServerStreamPingPongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStreamPingPongRequest.Unmarshal(m, b)
}
func (m *ServerStreamPingPongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStreamPingPongRequest.Marshal(b, m, deterministic)
}
func (m *ServerStreamPingPongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStreamPingPongRequest.Merge(m, src)
}
func (m *ServerStreamPingPongRequest) XXX_Size() int {
	return xxx_messageInfo_ServerStreamPingPongRequest.Size(m)
}
func (m *ServerStreamPingPongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStreamPingPongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStreamPingPongRequest proto.InternalMessageInfo

func (m *ServerStreamPingPongRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

func (m *ServerStreamPingPongRequest) GetPingCount() int32 {
	if m != nil {
		return m.PingCount
	}
	return 0
}

func (m *ServerStreamPingPongRequest) GetPingInterval() int32 {
	if m != nil {
		return m.PingInterval
	}
	return 0
}

type ServerStreamPingPongResponse struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStreamPingPongResponse) Reset()         { *m = ServerStreamPingPongResponse{} }
func (m *ServerStreamPingPongResponse) String() string { return proto.CompactTextString(m) }
func (*ServerStreamPingPongResponse) ProtoMessage()    {}
func (*ServerStreamPingPongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0764852e9d3d2a10, []int{5}
}

func (m *ServerStreamPingPongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStreamPingPongResponse.Unmarshal(m, b)
}
func (m *ServerStreamPingPongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStreamPingPongResponse.Marshal(b, m, deterministic)
}
func (m *ServerStreamPingPongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStreamPingPongResponse.Merge(m, src)
}
func (m *ServerStreamPingPongResponse) XXX_Size() int {
	return xxx_messageInfo_ServerStreamPingPongResponse.Size(m)
}
func (m *ServerStreamPingPongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStreamPingPongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStreamPingPongResponse proto.InternalMessageInfo

func (m *ServerStreamPingPongResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "v1.PingRequest")
	proto.RegisterType((*PongResponse)(nil), "v1.PongResponse")
	proto.RegisterType((*FetchPingCountRequest)(nil), "v1.FetchPingCountRequest")
	proto.RegisterType((*FetchPingCountResponse)(nil), "v1.FetchPingCountResponse")
	proto.RegisterType((*ServerStreamPingPongRequest)(nil), "v1.ServerStreamPingPongRequest")
	proto.RegisterType((*ServerStreamPingPongResponse)(nil), "v1.ServerStreamPingPongResponse")
}

func init() { proto.RegisterFile("v1/ping_pong.proto", fileDescriptor_0764852e9d3d2a10) }

var fileDescriptor_0764852e9d3d2a10 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0xc7, 0xe5, 0x66, 0xdb, 0xfb, 0xf6, 0x59, 0x61, 0x9d, 0x35, 0x50, 0x09, 0x43, 0x98, 0x20,
	0xa1, 0x31, 0xd1, 0xa4, 0x29, 0x3d, 0xc1, 0x05, 0x98, 0x84, 0xc4, 0xad, 0xca, 0x6e, 0x70, 0x40,
	0x21, 0x7b, 0xe4, 0x1a, 0x15, 0xdb, 0xd8, 0x4e, 0xc6, 0x99, 0x33, 0x07, 0x04, 0x37, 0xbe, 0x16,
	0x5f, 0x81, 0x2f, 0xc1, 0x0d, 0xd9, 0x69, 0x45, 0xa1, 0x2d, 0xa7, 0x38, 0x7f, 0xff, 0xf2, 0xb7,
	0xfd, 0x8b, 0x81, 0x36, 0x79, 0xa6, 0x85, 0xe4, 0xaf, 0xb5, 0x92, 0x3c, 0xd5, 0x46, 0x39, 0x45,
	0x3b, 0x4d, 0x1e, 0x1f, 0x73, 0xa5, 0xf8, 0x1c, 0xb3, 0x52, 0x8b, 0xac, 0x94, 0x52, 0xb9, 0xd2,
	0x09, 0x25, 0x6d, 0x4b, 0xc4, 0x0f, 0xc2, 0xa3, 0x1a, 0x72, 0x94, 0x43, 0x7b, 0x59, 0x72, 0x8e,
	0x26, 0x53, 0x3a, 0x10, 0xeb, 0x74, 0x72, 0x07, 0xf6, 0xa7, 0x42, 0xf2, 0x02, 0xdf, 0xd7, 0x68,
	0x1d, 0xa5, 0xb0, 0xe3, 0x57, 0x1c, 0x10, 0x46, 0x4e, 0xba, 0x45, 0x18, 0x27, 0x09, 0xf4, 0xa6,
	0xca, 0x23, 0x56, 0x2b, 0x69, 0x31, 0x30, 0x6a, 0x85, 0x51, 0x92, 0x27, 0xf7, 0xe1, 0xda, 0x73,
	0x74, 0xd5, 0xcc, 0x77, 0x9d, 0xa9, 0x5a, 0xba, 0x65, 0x61, 0x1f, 0xa2, 0x52, 0x8b, 0x05, 0xeb,
	0x87, 0xc9, 0x13, 0xb8, 0xfe, 0x37, 0xba, 0x28, 0x5e, 0x63, 0xe9, 0x11, 0xec, 0x56, 0x1e, 0x19,
	0x74, 0x18, 0x39, 0x89, 0x8a, 0xf6, 0x25, 0xa9, 0xe1, 0xe6, 0x39, 0x9a, 0x06, 0xcd, 0xb9, 0x33,
	0x58, 0xbe, 0xf3, 0x45, 0xed, 0x06, 0xb7, 0x9e, 0x81, 0xde, 0x02, 0x08, 0x26, 0x7f, 0xb7, 0xed,
	0x16, 0x5d, 0xbd, 0xdc, 0x01, 0xbd, 0x0b, 0x57, 0xc2, 0xb4, 0x90, 0x0e, 0x4d, 0x53, 0xce, 0x07,
	0x51, 0x20, 0x7a, 0x3e, 0x7c, 0xb1, 0xc8, 0x92, 0x31, 0x1c, 0x6f, 0x5e, 0x76, 0xbb, 0x97, 0xf1,
	0x4f, 0x02, 0x07, 0x4b, 0xd0, 0x7f, 0x2c, 0x2a, 0xa4, 0x43, 0xf8, 0x7f, 0x19, 0xd1, 0x83, 0xb4,
	0xc9, 0xd3, 0x95, 0x1f, 0x10, 0xf7, 0x43, 0xb0, 0x5a, 0xfb, 0x12, 0xae, 0xfe, 0xe9, 0x8b, 0xde,
	0xf0, 0xcc, 0x46, 0xdd, 0x71, 0xbc, 0x69, 0xaa, 0x2d, 0x4a, 0x0e, 0x3f, 0x7e, 0xff, 0xf1, 0xb5,
	0xb3, 0x4f, 0xbb, 0x59, 0x93, 0x67, 0x41, 0x04, 0x7d, 0x05, 0x47, 0x9b, 0x8e, 0x44, 0x6f, 0xfb,
	0x9a, 0x7f, 0x38, 0x8e, 0xd9, 0x76, 0xa0, 0x5d, 0x6d, 0x44, 0x9e, 0x7d, 0x26, 0x5f, 0x9e, 0x7e,
	0x22, 0xf4, 0x1e, 0x1c, 0x7a, 0x8d, 0xcc, 0xfb, 0x60, 0xb6, 0x75, 0x90, 0xf4, 0x00, 0x0c, 0x96,
	0x95, 0x1b, 0xf2, 0x62, 0x7a, 0x36, 0x8e, 0xf2, 0x74, 0x74, 0x4a, 0xc8, 0xb8, 0x5f, 0x6a, 0x3d,
	0x17, 0x55, 0xb8, 0xa0, 0xd9, 0x5b, 0xab, 0xe4, 0xa3, 0xb5, 0xa4, 0x78, 0x0c, 0xd1, 0x64, 0x34,
	0xa1, 0x13, 0x38, 0x2d, 0xd0, 0xd5, 0x46, 0xe2, 0x05, 0xbb, 0x9c, 0xa1, 0x64, 0x6e, 0x86, 0xcc,
	0xa0, 0x55, 0xb5, 0xa9, 0x90, 0x5d, 0x28, 0xb4, 0x4c, 0x2a, 0xc7, 0xf0, 0x83, 0xb0, 0x2e, 0xa5,
	0x7b, 0xb0, 0xf3, 0xad, 0x43, 0xfe, 0x7b, 0xb3, 0x17, 0x2e, 0xfd, 0xc3, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xed, 0xc0, 0xe0, 0xcc, 0x5a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingPongServiceClient is the client API for PingPongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingPongServiceClient interface {
	PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
	FetchPingCount(ctx context.Context, in *FetchPingCountRequest, opts ...grpc.CallOption) (*FetchPingCountResponse, error)
	ServerStreamPingPong(ctx context.Context, in *ServerStreamPingPongRequest, opts ...grpc.CallOption) (PingPongService_ServerStreamPingPongClient, error)
}

type pingPongServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingPongServiceClient(cc *grpc.ClientConn) PingPongServiceClient {
	return &pingPongServiceClient{cc}
}

func (c *pingPongServiceClient) PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/v1.PingPongService/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongServiceClient) FetchPingCount(ctx context.Context, in *FetchPingCountRequest, opts ...grpc.CallOption) (*FetchPingCountResponse, error) {
	out := new(FetchPingCountResponse)
	err := c.cc.Invoke(ctx, "/v1.PingPongService/FetchPingCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongServiceClient) ServerStreamPingPong(ctx context.Context, in *ServerStreamPingPongRequest, opts ...grpc.CallOption) (PingPongService_ServerStreamPingPongClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingPongService_serviceDesc.Streams[0], "/v1.PingPongService/ServerStreamPingPong", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongServiceServerStreamPingPongClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingPongService_ServerStreamPingPongClient interface {
	Recv() (*ServerStreamPingPongResponse, error)
	grpc.ClientStream
}

type pingPongServiceServerStreamPingPongClient struct {
	grpc.ClientStream
}

func (x *pingPongServiceServerStreamPingPongClient) Recv() (*ServerStreamPingPongResponse, error) {
	m := new(ServerStreamPingPongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingPongServiceServer is the server API for PingPongService service.
type PingPongServiceServer interface {
	PingPong(context.Context, *PingRequest) (*PongResponse, error)
	FetchPingCount(context.Context, *FetchPingCountRequest) (*FetchPingCountResponse, error)
	ServerStreamPingPong(*ServerStreamPingPongRequest, PingPongService_ServerStreamPingPongServer) error
}

func RegisterPingPongServiceServer(s *grpc.Server, srv PingPongServiceServer) {
	s.RegisterService(&_PingPongService_serviceDesc, srv)
}

func _PingPongService_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServiceServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PingPongService/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServiceServer).PingPong(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPongService_FetchPingCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPingCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServiceServer).FetchPingCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PingPongService/FetchPingCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServiceServer).FetchPingCount(ctx, req.(*FetchPingCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPongService_ServerStreamPingPong_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamPingPongRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingPongServiceServer).ServerStreamPingPong(m, &pingPongServiceServerStreamPingPongServer{stream})
}

type PingPongService_ServerStreamPingPongServer interface {
	Send(*ServerStreamPingPongResponse) error
	grpc.ServerStream
}

type pingPongServiceServerStreamPingPongServer struct {
	grpc.ServerStream
}

func (x *pingPongServiceServerStreamPingPongServer) Send(m *ServerStreamPingPongResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PingPongService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PingPongService",
	HandlerType: (*PingPongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _PingPongService_PingPong_Handler,
		},
		{
			MethodName: "FetchPingCount",
			Handler:    _PingPongService_FetchPingCount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamPingPong",
			Handler:       _PingPongService_ServerStreamPingPong_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/ping_pong.proto",
}
