// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping_pong.proto

package pingpong

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3b7dc6af2be2fc, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PongResponse struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongResponse) Reset()         { *m = PongResponse{} }
func (m *PongResponse) String() string { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()    {}
func (*PongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3b7dc6af2be2fc, []int{1}
}

func (m *PongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongResponse.Unmarshal(m, b)
}
func (m *PongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongResponse.Marshal(b, m, deterministic)
}
func (m *PongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongResponse.Merge(m, src)
}
func (m *PongResponse) XXX_Size() int {
	return xxx_messageInfo_PongResponse.Size(m)
}
func (m *PongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PongResponse proto.InternalMessageInfo

func (m *PongResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type FetchPingCountRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPingCountRequest) Reset()         { *m = FetchPingCountRequest{} }
func (m *FetchPingCountRequest) String() string { return proto.CompactTextString(m) }
func (*FetchPingCountRequest) ProtoMessage()    {}
func (*FetchPingCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3b7dc6af2be2fc, []int{2}
}

func (m *FetchPingCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPingCountRequest.Unmarshal(m, b)
}
func (m *FetchPingCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPingCountRequest.Marshal(b, m, deterministic)
}
func (m *FetchPingCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPingCountRequest.Merge(m, src)
}
func (m *FetchPingCountRequest) XXX_Size() int {
	return xxx_messageInfo_FetchPingCountRequest.Size(m)
}
func (m *FetchPingCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPingCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPingCountRequest proto.InternalMessageInfo

func (m *FetchPingCountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type FetchPingCountResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Ping total count
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchPingCountResponse) Reset()         { *m = FetchPingCountResponse{} }
func (m *FetchPingCountResponse) String() string { return proto.CompactTextString(m) }
func (*FetchPingCountResponse) ProtoMessage()    {}
func (*FetchPingCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3b7dc6af2be2fc, []int{3}
}

func (m *FetchPingCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchPingCountResponse.Unmarshal(m, b)
}
func (m *FetchPingCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchPingCountResponse.Marshal(b, m, deterministic)
}
func (m *FetchPingCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchPingCountResponse.Merge(m, src)
}
func (m *FetchPingCountResponse) XXX_Size() int {
	return xxx_messageInfo_FetchPingCountResponse.Size(m)
}
func (m *FetchPingCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchPingCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchPingCountResponse proto.InternalMessageInfo

func (m *FetchPingCountResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FetchPingCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pingpong.PingRequest")
	proto.RegisterType((*PongResponse)(nil), "pingpong.PongResponse")
	proto.RegisterType((*FetchPingCountRequest)(nil), "pingpong.fetchPingCountRequest")
	proto.RegisterType((*FetchPingCountResponse)(nil), "pingpong.fetchPingCountResponse")
}

func init() { proto.RegisterFile("ping_pong.proto", fileDescriptor_fc3b7dc6af2be2fc) }

var fileDescriptor_fc3b7dc6af2be2fc = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xe5, 0x66, 0x59, 0xd8, 0xd9, 0x15, 0xbb, 0x6b, 0xd1, 0xaa, 0x8a, 0x90, 0x30, 0x39,
	0xa0, 0x52, 0xd1, 0xa4, 0x2d, 0xbd, 0x00, 0x17, 0xa0, 0x2f, 0x50, 0x85, 0x07, 0x40, 0x21, 0x9d,
	0xba, 0x46, 0x95, 0xc7, 0xc4, 0x4e, 0xcb, 0x99, 0x33, 0x07, 0x04, 0x37, 0x9e, 0x83, 0x37, 0xe1,
	0x15, 0x78, 0x10, 0x64, 0xa7, 0x15, 0x81, 0xb2, 0xa7, 0xcc, 0xfc, 0xfa, 0xe6, 0xcf, 0x3f, 0x93,
	0xc0, 0xa5, 0x51, 0x5a, 0xbe, 0x35, 0xa4, 0x65, 0x6a, 0x2a, 0x72, 0xc4, 0xef, 0x78, 0xc1, 0xf7,
	0xf1, 0x7d, 0x49, 0x24, 0x37, 0x98, 0x15, 0x46, 0x65, 0x85, 0xd6, 0xe4, 0x0a, 0xa7, 0x48, 0xdb,
	0x86, 0x8b, 0x9f, 0x84, 0x47, 0x39, 0x92, 0xa8, 0x47, 0x76, 0x57, 0x48, 0x89, 0x55, 0x46, 0x26,
	0x10, 0xc7, 0x74, 0xf2, 0x10, 0xce, 0x17, 0x4a, 0xcb, 0x1c, 0x3f, 0xd4, 0x68, 0x1d, 0xe7, 0x70,
	0xe2, 0x5f, 0xd3, 0x67, 0x82, 0x0d, 0xce, 0xf2, 0x50, 0x27, 0x09, 0x5c, 0x2c, 0xc8, 0x23, 0xd6,
	0x90, 0xb6, 0x18, 0x18, 0x6a, 0x31, 0xa4, 0x65, 0xf2, 0x18, 0xba, 0x2b, 0x74, 0xe5, 0xda, 0x7b,
	0xcd, 0xa9, 0xd6, 0xee, 0x60, 0x78, 0x05, 0x51, 0x61, 0xd4, 0x9e, 0xf5, 0x65, 0xf2, 0x12, 0x7a,
	0xff, 0xa2, 0x7b, 0xe3, 0x23, 0x96, 0xdf, 0x83, 0x5b, 0xa5, 0x47, 0xfa, 0x1d, 0xc1, 0x06, 0x51,
	0xde, 0x34, 0xd3, 0x1f, 0x0c, 0x2e, 0xfd, 0xb4, 0x4f, 0xf5, 0x06, 0xab, 0xad, 0x2a, 0x91, 0x3f,
	0x83, 0x70, 0x1f, 0x2f, 0xf1, 0x6e, 0x7a, 0x38, 0x55, 0xda, 0xda, 0x2d, 0xee, 0xb5, 0xe4, 0xf6,
	0x3e, 0x2b, 0xb8, 0xfb, 0x77, 0x20, 0xfe, 0xe0, 0x0f, 0xf9, 0xdf, 0xad, 0x62, 0x71, 0x33, 0xd0,
	0x98, 0x26, 0xd7, 0x9f, 0x7e, 0xfe, 0xfa, 0xd6, 0x39, 0xe7, 0x67, 0xd9, 0x76, 0x92, 0x85, 0xd8,
	0xaf, 0xbf, 0xb0, 0xaf, 0xaf, 0x3e, 0x33, 0xfe, 0x08, 0xae, 0xfd, 0xb0, 0xf0, 0xd3, 0xc2, 0x36,
	0xf1, 0x93, 0x0b, 0x80, 0x0a, 0x8b, 0xd2, 0x8d, 0x64, 0xbe, 0x98, 0x4f, 0xa3, 0x49, 0x3a, 0x1e,
	0x32, 0x36, 0xbd, 0x2a, 0x8c, 0xd9, 0xa8, 0x32, 0x7c, 0xb0, 0xec, 0xbd, 0x25, 0xfd, 0xfc, 0x48,
	0xc9, 0x5f, 0x40, 0x34, 0x1b, 0xcf, 0xf8, 0x0c, 0x86, 0x39, 0xba, 0xba, 0xd2, 0xb8, 0x14, 0xbb,
	0x35, 0x6a, 0xe1, 0xd6, 0x28, 0x2a, 0xb4, 0x54, 0x57, 0x25, 0x8a, 0x25, 0xa1, 0x15, 0x9a, 0x9c,
	0xc0, 0x8f, 0xca, 0xba, 0x94, 0x9f, 0xc2, 0xc9, 0xf7, 0x0e, 0xbb, 0xfd, 0xee, 0x34, 0xfc, 0x04,
	0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xef, 0x85, 0x10, 0x6d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingPongServiceClient is the client API for PingPongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingPongServiceClient interface {
	PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
	FetchPingCount(ctx context.Context, in *FetchPingCountRequest, opts ...grpc.CallOption) (*FetchPingCountResponse, error)
}

type pingPongServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingPongServiceClient(cc *grpc.ClientConn) PingPongServiceClient {
	return &pingPongServiceClient{cc}
}

func (c *pingPongServiceClient) PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/pingpong.PingPongService/pingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongServiceClient) FetchPingCount(ctx context.Context, in *FetchPingCountRequest, opts ...grpc.CallOption) (*FetchPingCountResponse, error) {
	out := new(FetchPingCountResponse)
	err := c.cc.Invoke(ctx, "/pingpong.PingPongService/fetchPingCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongServiceServer is the server API for PingPongService service.
type PingPongServiceServer interface {
	PingPong(context.Context, *PingRequest) (*PongResponse, error)
	FetchPingCount(context.Context, *FetchPingCountRequest) (*FetchPingCountResponse, error)
}

func RegisterPingPongServiceServer(s *grpc.Server, srv PingPongServiceServer) {
	s.RegisterService(&_PingPongService_serviceDesc, srv)
}

func _PingPongService_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServiceServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPongService/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServiceServer).PingPong(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPongService_FetchPingCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPingCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServiceServer).FetchPingCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPongService/FetchPingCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServiceServer).FetchPingCount(ctx, req.(*FetchPingCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPongService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingPongService",
	HandlerType: (*PingPongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pingPong",
			Handler:    _PingPongService_PingPong_Handler,
		},
		{
			MethodName: "fetchPingCount",
			Handler:    _PingPongService_FetchPingCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping_pong.proto",
}
